ex(1,parse([the,dog,walks,to,the,man]),1).
ex(2,parse([the,man,walks,the,dog]),1).
ex(3,parse([a,dog,hits,a,ball]),1).
ex(4,parse([the,man,walks,in,the,house]),1).
ex(5,parse([the,man,walks,into,a,house]),1).
ex(6,parse([the,man,hits,the,dog]),1).
ex(7,parse([a,ball,hits,the,dog]),1).
ex(8,parse([the,dog,walks,on,the,house]),1).
ex(9,parse([the,man,hits,at,the,ball]),1).
ex(10,parse([the,big,man,hits,at,the,ball]),1).
ex(11,parse([the,small,dog,walks,on,the,house]),1).
ex(12,parse([the,small,dog,walks,in,the,house]),1).
ex(13,parse([the,small,dog,walks,into,the,house]),1).
ex(14,parse([the,small,man,hits,the,dog]),1).
ex(15,parse([the,big,man,hits,the,dog]),1).
ex(16,parse([a,ball,hits,the,small,dog]),1).
ex(17,parse([the,nasty,man,hits,the,dog]),1).
ex(18,parse([the,man,hits,the,nasty,dog]),1).
ex(19,parse([a,man,hits,the,ball,at,the,dog]),1).
ex(20,parse([the,man,hits,the,ball,at,the,house]),1).
ex(21,parse([the,man,takes,the,dog,to,the,ball]),1).
ex(22,parse([a,man,takes,the,ball,to,the,house]),1).
ex(23,parse([the,dog,takes,the,ball,to,the,house]),1).
ex(24,parse([the,dog,takes,the,ball,to,the,man]),1).
ex(25,parse([the,man,hits,the,ball,to,the,dog]),1).
ex(26,parse([dog,the,the,walks,to,man]),0).
ex(27,parse([dog,the,man,the,walks]),0).
ex(28,parse([ball,a,dog,a,hits]),0).
ex(29,parse([in,the,house,the,walks,man]),0).
ex(30,parse([the,man,the,house,into,walks]),0).
ex(31,parse([man,the,hits,the,dog]),0).
ex(32,parse([a,man,walks,the,walks]),0).
ex(33,parse([the,the,house,dog,on,walks]),0).
ex(34,parse([the,hits,at,man,the,ball]),0).
ex(35,parse([at,hits,the,the,man,big,ball]),0).
ex(36,parse([the,the,walks,on,dog,house,small]),0).
ex(37,parse([a,dog,walks,the]),0).
ex(38,parse([the,house,the,dog,walks,into,small]),0).
ex(39,parse([the,hits,small,the,dog,man]),0).
ex(40,parse([the,the,big,hits,dog,man]),0).
ex(41,parse([dog,small,hits,a,ball,the]),0).
ex(42,parse([the,man,dog,hits,nasty,the]),0).
ex(43,parse([dog,the,man]),0).
ex(44,parse([hits,the,at,ball,dog,man,a,the]),0).
ex(45,parse([the,man,the,hits,house,ball,at,the]),0).
ex(46,parse([the,dog,takes,the,the,man,to,ball]),0).
ex(47,parse([to,takes,the,man,a,ball,the,house]),0).
ex(48,parse([dog,the,the,to,takes,ball,house,the]),0).
ex(49,parse([ball,dog,the,the,takes,man,the,to]),0).
ex(50,parse([to,the,house,walks,the,dog]),0). 